#!/bin/sh

# TODO remove AWS_ACCESS_KEYS, DOCKER_AUTH from secrets/*
# TODO change cencosud-ds for paristech
# TODO remove all null files
# using a NOT operation to include the "*" scoped variables
# EXCLUDED_ENVIRONMENT="prd"
# PROJECT_ID="19799255"
22283636

# # get key,values environment variables from gitlab as json
curl -s --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/${PROJECT_ID}/variables" | \
  jq --arg environment "$EXCLUDED_ENVIRONMENT" '.[] |= select(.environment_scope!=$environment) | del(..|nulls) | map( { (.key): .value } ) | add' \
  > test.json

# create secret with file
aws secretsmanager create-secret \
    --name test-deleteme2 \
    --description "just a test" \
    --secret-string file://test.json \
    --region us-east-1

# # get all projects from cencosud-ds
# while true; do 
#   ((counter++)) 
#   curl -s --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" --request GET "https://gitlab.com/api/v4/groups/3108929/projects?per_page=100&page=${counter}&include_subgroups=true" | jq -r '.[]' >> projects100.json
#   echo $counter
# done

# # select project based on .id
# cat projects100.json | jq 'select(.id == 19799255)'

# # get path_with_namespace from list of repos to pass to infra
# while read line; do
#   echo $line | awk -F ':' '{print $2}' | cut -d. -f1 >> path_with_namespace.txt
# done <<< $(cat repos.txt)

# Generate JSON from Gitlab Variables of every project managed by ArgoCD
while read line; do
  mkdir -p secrets
  FILENAME=secrets/$(tr '/' '_' <<< $line).json
  PROJECT_ID=$(cat projects100.json | \
    jq --arg line "$line" 'select(.path_with_namespace == $line) | .id')
  echo $PROJECT_ID
  curl -s --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/${PROJECT_ID}/variables?per_page=100" | \
    jq '.[] |= select(.environment_scope!="prd" and .environment_scope!="prod" and .environment_scope!="production") | del(..|nulls) | map( { (.key): .value } ) | add' \
    > $FILENAME
    cat $FILENAME
done <<< $(cat path_with_namespace.txt)
