#!/bin/sh

# using a NOT operation to include the "*" scoped variables
EXCLUDED_ENVIRONMENT="dev"
PROJECT_ID="19799255"

# get key,values environment variables from gitlab as json
curl -s --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/${PROJECT_ID}/variables" | \
  jq --arg environment "$EXCLUDED_ENVIRONMENT" '.[] |= select(.environment_scope!=$environment) | del(..|nulls) | map( { (.key): .value } ) | add' \
  > test.json

# # create secret with file
# aws secretsmanager create-secret \
#     --name test-deleteme2 \
#     --description "just a test" \
#     --secret-string file://test.json \
#     --region us-east-1
