#!/bin/sh
#
# For creating & setting permissions of script file for bash/python
# TODO: Check if file already exists before touch & validate that $2 isn't empty

FILENAME=$1
TYPE=$2
DIR=$HOME/.local/bin
FPATH=$DIR/$FILENAME

touch $FPATH

if [[ $2 = "bash" ]]; then
    echo -e "#!/bin/sh\n#\n" > $FPATH
elif [[ $2 = "python" ]]; then
    echo -e "#!/bin/env python3\n#\n" > $FPATH
fi

chmod 755 $FPATH
$EDITOR $FPATH


