#!/bin/zsh

#For some reason can't run it locally with the shebang to sh

#First script
#Cycle through imgs in fullscreen & set your wallpaper with <enter>

DIR=$HOME/wallpapers
SET_WALLP="feh --bg-fill %F | pkill -f feh"

feh $DIR --sort filename --fullscreen --zoom fill --action $SET_WALLP

#gotta wait for .fehbg to be made
sleep 2 &
wait

#dont mess up your home
mv $HOME/.fehbg $HOME/.local/bin/.fehbg

#f toggle fullscreen
#/(keypad) scale to screen size
#q quit
#n-p next-previous
#d toogle img name/number
